### PR TITLE
Fix for standalone building of SPD-Metamodel

### PR DESCRIPTION
**Pull request by noahrog02**
Target Platform of Slingshot allows all Dependencies to be resolved successfully. Category.xml is no longer needed. Unused Dependencies in Target Platform may be deleted

### CODE REVIEW

**Review by stiesssh — COMMENTED** [review]
I tried this out, it worked. 

I suggest to create a separate PR for the refactoring of the TargetPlatform. 

Lastly: i'm not sure about the deletiong of the category xml, that why there is not yet an "approve".

**Comment by klinakuf** [comment]
* Cleaned up the target platform with a minimal set of dependencies 
* The building works, and an installable feature is generated.

**Review by klinakuf — APPROVED** [review]

**Review by stiesssh — APPROVED** [review]
builds on my machine. 

category looks good to me as well.

**Comment by klinakuf** [comment]
already merged https://github.com/PalladioSimulator/Palladio-Addons-SPD-Metamodel/pull/29

**Pull request closed without merging**
